import { describe, expect, it } from "vitest";
import { buildHealthReportPdfs, getHealthReportFilenames } from "./healthReportPdf";

describe("readable health report PDFs", () => {
  const exportedAt = new Date(2026, 8, 7, 4, 41, 32);
  const data = {
    patientName: "Alex",
    units: "lbs",
    doses: [{
      id: "dose-1",
      date: "2026-09-06",
      time: "09:00",
      doseAmount: 1,
      site: "abdomen",
      notes: "Recorded note",
      taken: true,
      sideEffects: ["Nausea"],
    }],
    weights: [{
      id: "weight-1",
      date: "2026-09-06",
      weight: 176.4,
      notes: "Morning reading",
    }],
  };

  it("uses unique date-and-time filenames for every report", () => {
    expect(getHealthReportFilenames(exportedAt)).toEqual({
      doses: "jotrea-doses-2026-09-07-044132.pdf",
      weights: "jotrea-weights-2026-09-07-044132.pdf",
      symptoms: "jotrea-symptoms-2026-09-07-044132.pdf",
    });
  });

  it("creates all three readable reports with their complete recorded content", () => {
    const reports = buildHealthReportPdfs(data, exportedAt);
    expect(reports.map((report) => report.slug)).toEqual(["doses", "weights", "symptoms"]);
    const output = reports.map((report) => report.doc.output()).join("\n");
    expect(output).toContain("Jotrea Health Report");
    expect(output).toContain("Dose History");
    expect(output).toContain("Weight History");
    expect(output).toContain("Symptom History");
    expect(output).toContain("Recorded note");
    expect(output).toContain("176.4");
    expect(output).toContain("Nausea");
    expect(output).toContain("Generated by Jotrea");
  });

  it("paginates long histories without dropping records", () => {
    const reports = buildHealthReportPdfs({
      ...data,
      doses: Array.from({ length: 80 }, (_, index) => ({
        ...data.doses[0],
        id: `dose-${index}`,
        notes: `Recorded note ${index} `.repeat(4),
      })),
    }, exportedAt);
    const doseReport = reports.find((report) => report.slug === "doses");
    expect(doseReport?.doc.getNumberOfPages()).toBeGreaterThan(1);
    expect(doseReport?.doc.output()).toContain("Recorded note 79");
  });
});